import React,{useMemo,useState} from 'react'
import {solveFrame2D,type FrameModel} from '../../engineering/core/frame2d'
import {isolatedFootingPro} from '../foundationsPro/FoundationsSolver'
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
const M=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>
function makeFrame(floors:number,bays:number,bay:number,storey:number,q:number,H:number):FrameModel{
 const ns:any[]=[],es:any[]=[];let eid=1
 for(let j=0;j<=floors;j++)for(let i=0;i<=bays;i++){const id=j*(bays+1)+i+1;ns.push({id,x:i*bay,y:j*storey,...(j===0?{fixX:true,fixY:true,fixR:true}:{}),...(j===floors&&i===bays?{Fx:H*1000}:{})})}
 for(let j=0;j<floors;j++)for(let i=0;i<=bays;i++){const a=j*(bays+1)+i+1,b=(j+1)*(bays+1)+i+1;es.push({id:eid++,a,b,E:30e9,A:.12,I:.0016})}
 for(let j=1;j<=floors;j++)for(let i=0;i<bays;i++){const a=j*(bays+1)+i+1,b=a+1;es.push({id:eid++,a,b,E:30e9,A:.15,I:.003,qy:-q*1000})}
 return{nodes:ns,elements:es}
}
export default function BuildingModelPage(){
 const[floors,setFloors]=useState(3),[bays,setBays]=useState(2),[bay,setBay]=useState(5),[storey,setStorey]=useState(3),[q,setQ]=useState(12),[wind,setWind]=useState(25),[FB,setFB]=useState(2.4),[FL,setFL]=useState(2.4),[fh,setFh]=useState(.6),[qadm,setQadm]=useState(250)
 const nf=Math.max(1,Math.min(6,Math.round(floors))),nb=Math.max(1,Math.min(5,Math.round(bays))),model=useMemo(()=>makeFrame(nf,nb,bay,storey,q,wind),[nf,nb,bay,storey,q,wind])
 const solved=useMemo(()=>{try{return{r:solveFrame2D(model),err:''}}catch(e){return{r:null,err:e instanceof Error?e.message:String(e)}}},[model])
 const bases=model.nodes.filter(n=>n.y===0)
 const foundations=solved.r?bases.map(n=>{const i=model.nodes.findIndex(x=>x.id===n.id),Rx=solved.r!.reactions[3*i]/1000,Ry=solved.r!.reactions[3*i+1]/1000,Mm=solved.r!.reactions[3*i+2]/1000,N=Math.max(0,Ry);const f=isolatedFootingPro({N,Hx:Math.abs(Rx),Hy:0,Mx:Math.abs(Mm),My:0,B:FB,L:FL,h:fh,cb:.35,cl:.45,cover:.05,qAllow:qadm,mu:.5,fck:30,fyk:500,phi:12});return{id:n.id,Rx,Ry,M:Mm,...f}}):[]
 const maxDisp=solved.r?Math.max(...model.nodes.map((_,i)=>Math.hypot(solved.r!.displacements[3*i],solved.r!.displacements[3*i+1]))):0
 return <div className="module-page"><div className="module-head"><div><h2>Modelo de Edifício · V62</h2><p>Gerador paramétrico de pisos e vãos → análise do pórtico → reações → fundações automáticas.</p></div></div>
 <div className="work-grid"><section className="panel"><h3>Edifício</h3><div className="form-grid"><F l="Pisos" v={floors} s={setFloors}/><F l="Vãos" v={bays} s={setBays}/><F l="Largura vão" u="m" v={bay} s={setBay}/><F l="Pé-direito" u="m" v={storey} s={setStorey}/><F l="q vigas" u="kN/m" v={q} s={setQ}/><F l="Ação horizontal topo" u="kN" v={wind} s={setWind}/></div><h3>Fundação tipo</h3><div className="form-grid"><F l="B" u="m" v={FB} s={setFB}/><F l="L" u="m" v={FL} s={setFL}/><F l="h" u="m" v={fh} s={setFh}/><F l="qadm" u="kPa" v={qadm} s={setQadm}/></div></section><section className="panel"><h3>Modelo gerado</h3><BuildingSvg model={model}/>{solved.err&&<div className="solver-error">{solved.err}</div>}</section></div>
 {solved.r&&<><div className="result-grid"><M t="Nós" v={`${model.nodes.length}`}/><M t="Barras" v={`${model.elements.length}`}/><M t="Pilares de base" v={`${bases.length}`}/><M t="Desloc. máx." v={`${(maxDisp*1000).toFixed(2)} mm`}/></div>
 <section className="panel"><h3>Fundações geradas automaticamente</h3><div className="member-table">{foundations.map((f,k)=><div key={f.id}><b>F{k+1} · Nó {f.id}</b><span>N {f.Ry.toFixed(1)} kN</span><span>H {Math.abs(f.Rx).toFixed(1)} kN</span><span>M {f.M.toFixed(1)} kN·m</span><span>qmax {f.qmax.toFixed(1)} kPa</span><span>Terreno {(100*f.bearingUtil).toFixed(0)}%</span><span>{f.ok?'OK':'REVER'}</span></div>)}</div></section>
 <section className="panel"><h3>Fluxo automático V62</h3><div className="flow-line"><b>Pisos + vãos</b><span>→</span><b>Geometria</b><span>→</span><b>Solver matricial</b><span>→</span><b>Reações</b><span>→</span><b>{bases.length} fundações</b></div><p className="note">Modelo paramétrico 2D para estudo/pré-dimensionamento. Nesta fase todas as vigas e pilares usam propriedades padrão e todas as fundações partem da mesma geometria tipo. A próxima evolução pode otimizar cada secção e cada sapata individualmente.</p></section></>}</div>}
function BuildingSvg({model}:{model:FrameModel}){const W=650,H=430,p=50,mx=Math.max(...model.nodes.map(n=>n.x),1),my=Math.max(...model.nodes.map(n=>n.y),1),s=Math.min((W-2*p)/mx,(H-2*p)/my),P=(n:any)=>({x:p+n.x*s,y:H-p-n.y*s});return <svg viewBox={`0 0 ${W} ${H}`} className="eng-svg">{model.elements.map(e=>{const a=P(model.nodes.find(n=>n.id===e.a)!),b=P(model.nodes.find(n=>n.id===e.b)!);return <line key={e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#a9bacd" strokeWidth="5"/>})}{model.nodes.map(n=>{const q=P(n);return <circle key={n.id} cx={q.x} cy={q.y} r="5" fill={n.y===0?'#2dd4bf':'#e7eef6'}/>})}<text x="20" y="25" fill="#9fb3c8">Pórtico gerado automaticamente</text></svg>}