import React,{useMemo,useState} from 'react'; import {solveSlab} from './SlabSolver'; import {fmt} from '../../engineering/structuralMath'
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
export default function SlabsProPage(){const[lx,setLx]=useState(4.5),[ly,setLy]=useState(5.5),[gk,setG]=useState(5),[qk,setQ]=useState(3),[t,setT]=useState(.18),[cover,setC]=useState(.025),[fyk,setFyk]=useState(500),[support,setSupport]=useState<'simple'|'continuous'>('simple')
  const r=useMemo(()=>solveSlab({lx,ly,gk,qk,t,cover,fyk,support}),[lx,ly,gk,qk,t,cover,fyk,support])
  return <div className="module-page"><div className="module-head"><div><h2>Lajes</h2><p>Unidirecional/bidirecional, ações e armaduras preliminares.</p></div></div>
  <div className="tabs-row"><button className={support==='simple'?'active':''} onClick={()=>setSupport('simple')}>Simplesmente apoiada</button><button className={support==='continuous'?'active':''} onClick={()=>setSupport('continuous')}>Contínua</button></div><div className="work-grid"><section className="panel"><h3>Geometria e ações</h3><div className="form-grid"><F l="lx" u="m" v={lx} s={setLx}/><F l="ly" u="m" v={ly} s={setLy}/><F l="gk" u="kN/m²" v={gk} s={setG}/><F l="qk" u="kN/m²" v={qk} s={setQ}/><F l="Espessura" u="m" v={t} s={setT}/><F l="Recobrimento" u="m" v={cover} s={setC}/><F l="fyk" u="MPa" v={fyk} s={setFyk}/></div></section>
  <section className="panel"><h3>Modelo</h3><SlabSvg lx={lx} ly={ly} twoWay={r.twoWay}/></section></div>
  <div className="result-grid"><M t="Comportamento" v={r.twoWay?'Bidirecional':'Unidirecional'}/><M t="qEd" v={`${fmt(r.qEd)} kN/m²`}/><M t="Mx" v={`${fmt(r.Mx)} kN·m/m`}/><M t="My" v={`${fmt(r.My)} kN·m/m`}/><M t="Asx" v={`${fmt(r.Asx,0)} mm²/m`}/><M t="Asy" v={`${fmt(r.Asy,0)} mm²/m`}/><M t="M- x" v={`${fmt(r.MnegX)} kN·m/m`}/></div></div>}
const M=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>
function SlabSvg({lx,ly,twoWay}:{lx:number,ly:number,twoWay:boolean}){return <svg viewBox="0 0 500 300" className="eng-svg"><rect x="90" y="45" width="320" height="200" fill="#31455f" stroke="#8db4dd" strokeWidth="4"/>{Array.from({length:8}).map((_,i)=><line key={'x'+i} x1={110+i*40} y1="55" x2={110+i*40} y2="235" stroke="#ef6b6b" strokeWidth="2"/>)}{twoWay&&Array.from({length:5}).map((_,i)=><line key={'y'+i} x1="100" y1={70+i*38} x2="400" y2={70+i*38} stroke="#38bdf8" strokeWidth="2"/>)}<text x="190" y="280" fill="#9fb3c8">{lx.toFixed(2)} × {ly.toFixed(2)} m</text></svg>}
