export type ModuleId =
  | 'dashboard'
  | 'beams'
  | 'frames'
  | 'trusses'
  | 'columns'
  | 'slabs'
  | 'foundations'
  | 'walls'
  | 'geotechnics'
  | 'slopes'
  | 'hydraulics'
  | 'roads'
  | 'cycleways'
  | 'roundabouts'
  | 'library'
  | 'tools'
  | 'settings'
