import React,{useMemo,useState} from 'react'; import {solveTruss,type TrussType} from './TrussSolver'; import {fmt} from '../../engineering/structuralMath'
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
export default function TrussesProPage(){const[type,setType]=useState<TrussType>('pratt'),[L,setL]=useState(12),[H,setH]=useState(2.5),[panels,setPanels]=useState(6),[P,setP]=useState(25),[A,setA]=useState(.003),[E,setE]=useState(200); const r=useMemo(()=>solveTruss({L,H,panels,P,type,A,E}),[L,H,panels,P,type,A,E])
return <div className="module-page"><div className="module-head"><div><h2>Treliças</h2><p>Pratt, Howe e Warren, geometria e esforços aproximados.</p></div></div>
<div className="tabs-row">{(['pratt','howe','warren'] as TrussType[]).map(x=><button className={type===x?'active':''} onClick={()=>setType(x)} key={x}>{x.toUpperCase()}</button>)}</div>
<div className="work-grid"><section className="panel"><h3>Dados</h3><div className="form-grid"><F l="Vão" u="m" v={L} s={setL}/><F l="Altura" u="m" v={H} s={setH}/><F l="Painéis" v={panels} s={setPanels}/><F l="Carga por nó" u="kN" v={P} s={setP}/><F l="Área barra" u="m²" v={A} s={setA}/><F l="E" u="GPa" v={E} s={setE}/></div></section><section className="panel"><h3>Modelo</h3><TrussSvg L={L} H={H} n={r.n} type={type}/></section></div>
<div className="result-grid"><M t="RA" v={`${fmt(r.RA)} kN`}/><M t="RB" v={`${fmt(r.RB)} kN`}/><M t="Painel" v={`${fmt(r.panel)} m`}/><M t="Diagonal" v={`${fmt(r.diag)} m`}/><M t="Banzo aprox." v={`${fmt(r.chordApprox)} kN`}/><M t="Diagonal aprox." v={`${fmt(r.diagApprox)} kN`}/><M t="σ banzo" v={`${fmt(r.chordStress)} MPa`}/><M t="Flecha aprox." v={`${fmt(r.deflectionApprox*1000)} mm`}/></div></div>}
const M=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>
function TrussSvg({n,type}:{L:number,H:number,n:number,type:TrussType}){const x0=55,yb=210,yt=75,w=470,dx=w/n;let elems:any[]=[];for(let i=0;i<=n;i++){let x=x0+i*dx;elems.push(<circle key={'b'+i} cx={x} cy={yb} r="5" fill="#dbeafe"/>);if(i<n){elems.push(<line key={'bc'+i} x1={x} y1={yb} x2={x+dx} y2={yb} stroke="#9fb3c8" strokeWidth="4"/>);elems.push(<line key={'tc'+i} x1={x} y1={yt} x2={x+dx} y2={yt} stroke="#9fb3c8" strokeWidth="4"/>); if(type==='warren'){elems.push(<line key={'d'+i} x1={x} y1={i%2?yt:yb} x2={x+dx} y2={i%2?yb:yt} stroke="#39c6b6" strokeWidth="3"/>)}else{const flip=type==='howe';const y1=((i<n/2)!==flip)?yb:yt,y2=y1===yb?yt:yb;elems.push(<line key={'d'+i} x1={x} y1={y1} x2={x+dx} y2={y2} stroke="#39c6b6" strokeWidth="3"/>);}}}return <svg viewBox="0 0 580 280" className="eng-svg">{elems}</svg>}
